# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.destroy_all

User.create(nickname:'Blossom', email: 'amy.lewis@email.com', name: 'Amy Lewis', first_name: 'Amy', last_name: 'Lewis', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Los Angeles, CA', gender: 'F', uid: 1, has_tags: ['vehicle, bike'], want_tags: ['housing, pet, social'] )
User.create(nickname: 'CareBear', email: 'jenny.kim@email.com', name: 'Jenny Kim', first_name: 'Jenny', last_name: 'Kim', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Los Angeles, CA', gender: 'F', uid: 2, has_tags: ['vehicle, social'], want_tags: ['pet, housing, bike'] )
User.create(nickname: 'Jetson', email: 'michael.vallejo@email.com', name: 'Michael Vallejo', first_name: 'Michael', last_name: 'Vallejo', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 3, has_tags: ['bike, housing'], want_tags: ['pet, vehicle, social'] )
User.create(nickname: 'Scooby', email: 'sam.min@email.com', name: 'Sam Min', first_name: 'Sam', last_name: 'Min', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 4, has_tags: ['vehicle, bike'], want_tags: ['housing, pet, social'] )
User.create(nickname: 'Candyman', email: 'eugene.choi@email.com', name: 'Eugene Choi', first_name: 'Eugene', last_name: 'Choi', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 5, has_tags: ['vehicle, housing'], want_tags: ['bike, pet, social'] )
User.create(nickname: 'The Duke', email: 'george.sasscer@gmail.com', name: 'George Sasscer', first_name: 'George', last_name: 'Sasscer', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 6, has_tags: ['vehicle, pet'], want_tags: ['bike, pet'] )
User.create(nickname: 'The Duchess', email: 'Jackie Sasscer', name: 'Jackie Sasscer', first_name: 'Jackie', last_name: 'Sasscer', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Los Angeles, CA', gender: 'F', uid: 7, has_tags: ['pet, vehicle'], want_tags: ['bike, housing'] )
User.create(nickname: 'Ghostbuster', email: 'bill.oreilly@email.com', name: 'Bill O\'Reilly', first_name: 'Bill', last_name: 'O\'Reilly', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 8, has_tags: ['housing, topical'], want_tags: ['topical'] )
User.create(nickname: 'Han Solo', email: 'doug.funny@email.com', name: 'Doug Funny', first_name: 'Doug', last_name: 'Funny', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid: 9, has_tags: ['housing'], want_tags: ['bike'] )
User.create(nickname: 'Taco', email: 'lionel.ritchie@email.com', name: 'Lionel Ritchie', first_name: 'Lionel', last_name: 'Ritchie', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Los Angeles, CA', gender: 'M', uid:10, has_tags: ['vehicle, topical'], want_tags: ['topical'] )
User.create(nickname: 'Princess Leia', email: 'erin.huie@gmail.com', name: 'Erin Huie', first_name: 'Erin', last_name: 'Huie', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'San Francisco, CA', gender: 'F', uid:11, has_tags: ['topical'], want_tags: ['topical'] )
User.create(nickname: 'Foo', email: 'eugene.choi@email.com', name: 'Eugene Choi', first_name: 'Eugene', last_name: 'Choi', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 12, has_tags: ['bike, vehicle'], want_tags: ['housing'] )
User.create(nickname: 'Mario', email: 'ken.burns@email.com', name: 'Ken Burns', first_name: 'Ken', last_name: 'Burns', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 13, has_tags: ['vehicle, topical'], want_tags: ['topical'] )
User.create(nickname: 'Luigi', email: 'kevin.hart@gmail.com', name: 'Kevin Hart', first_name: 'Kevin', last_name: 'Hart', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 14, has_tags: ['topical, bike'], want_tags: ['housing'] )
User.create(nickname: 'Captain Kirk', email: 'james.t.kirk@gmail.com', name: 'James T. Kirk', first_name: 'James', last_name: 'Kirk', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 15, has_tags: ['topical, pet'], want_tags: ['topical, bike'] )
User.create(nickname: 'Sulu', email: 'george.takei@email.com', name: 'George Takei', first_name: 'George', last_name: 'Takei', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 16, has_tags: ['housing'], want_tags: ['pet'] )
User.create(nickname: 'Penny', email: 'penny.loafer@gmail.com', name: 'Penelope Lee', first_name: 'Penelope', last_name: 'Lee', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'San Francisco, CA', gender: 'F', uid: 17, has_tags: ['bike, housing'], want_tags: ['vehicle'] )
User.create(nickname: 'Manny', email: 'emmanuel.lee@email.com', name: 'Emmanuel Lee', first_name: 'Emmanuel', last_name: 'Lee', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 18, has_tags: ['topical'], want_tags: ['topical'] )
User.create(nickname: 'Granny', email: 'granny.smith@gmail.com', name: 'Greta Smith', first_name: 'Greta', last_name: 'Smith', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'San Francisco, CA', gender: 'F', uid: 19, has_tags: ['pet'], want_tags: ['housing'] )
User.create(nickname: 'Hunter', email: 'hunter.green@gmail.com', name: 'Harry Windsor', first_name: 'Harry', last_name: 'Windsor', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'San Francisco, CA', gender: 'M', uid: 20, has_tags: ['topical, bike'], want_tags: ['topical'] )
User.create(nickname: '', email: 'bob.oluwanda@gmail.com', name: 'Bob Oluwanda', first_name: 'Bob', last_name: 'Oluwanda', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Oakland, CA', gender: 'M', uid: 21, has_tags: ['bike'], want_tags: ['vehicle'] )
User.create(nickname: '', email: 'perry.biscuit@gmail.com', name: 'Perry Biscuit', first_name: 'Perry', last_name: 'Biscuit', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Oakland, CA', gender: 'M', uid: 22, has_tags: ['vehicle, housing'], want_tags: ['bike'] )
User.create(nickname: '', email: 'carmen.sandiego@gmail.com', name: 'Carmen San Diego', first_name: 'Carmen', last_name: 'San Diego', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Oakland, CA', gender: 'F', uid: 23, has_tags: ['housing, topical'], want_tags: ['bike, topical'] )
User.create(nickname: '', email: 'jasmine.bhambra@gmail.com', name: 'Jasmine Bhambra', first_name: 'Jasmine', last_name: 'Bhambra', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Oakland, CA', gender: 'F', uid: 24, has_tags: ['pet'], want_tags: ['vehicle'] )
User.create(nickname: '', email: 'aditi.uppal@email.com', name: 'Aditi Uppal', first_name: 'Aditi', last_name: 'Uppal', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Oakland, CA', gender: 'F', uid: 25, has_tags: ['vehicle, bike'], want_tags: ['pet'] )
User.create(nickname: '', email: 'matthew.tustison@gmail.com', name: 'Matt Tustison', first_name: 'Matt', last_name: 'Tustison', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Oakland, CA', gender: 'M', uid: 26, has_tags: ['pet, topical'], want_tags: ['topical'] )
User.create(nickname: '', email: 'karen.bonita@gmail.com', name: 'Karen Bonita', first_name: 'Karen', last_name: 'Bonita', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Oakland, CA', gender: 'F', uid: 27, has_tags: ['housing, pet'], want_tags: ['bike, housing'] )
User.create(nickname: '', email: 'josephine.Carillo@email.com', name: 'Josephine vehicleillo', first_name: 'Josephine', last_name: 'vehicleillo', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Oakland, CA', gender: 'F', uid: 28, has_tags: ['vehicle'], want_tags: ['bike, housing'] )
User.create(nickname: '', email: 'john.jones@gmail.com', name: 'John Jones', first_name: 'John', last_name: 'Jones', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Oakland, CA', gender: 'M', uid: 29, has_tags: ['vehicle, bike'], want_tags: ['housing'] )
User.create(nickname: '', email: 'mark.zuckerberg@email.com', name: 'Mark Zuckerberg', first_name: 'Mark', last_name: 'Zuckerberg', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Oakland, CA', gender: 'M', uid: 30, has_tags: ['topical'], want_tags: ['topical'] )
User.create(nickname: 'ZealousHacker', email: 'alex.notov@gmail.com', name: 'Alex Notov', first_name: 'Alex', last_name: 'Notov', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 31, has_tags: ['housing, vehicle'], want_tags: ['bike'] )
User.create(nickname: 'RadarScreen', email: 'paris.jones@gmail.com', name: 'Paris Jones', first_name: 'Paris', last_name: 'Jones', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'New York, NY', gender: 'F', uid: 32, has_tags: ['vehicle'], want_tags: ['housing'] )
User.create(nickname: 'Waldo', email: 'wally.gerhardt@gmail.com', name: 'Wally Gerhardt', first_name: 'Wally', last_name: 'Gerhardt', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 33, has_tags: ['housing, vehicle'], want_tags: ['bike'] )
User.create(nickname: 'Princess', email: 'peggy.tustison@gmail.com', name: 'Peggy Tustison', first_name: 'Peggy', last_name: 'Tustison', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'New York, NY', gender: 'F', uid: 34, has_tags: ['bike'], want_tags: ['housing'] )
User.create(nickname: 'Bologna', email: 'kim.west@gmail.com', name: 'Kim West', first_name: 'Kim', last_name: 'West', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'New York, NY', gender: 'F', uid: 35, has_tags: ['bike, topical'], want_tags: ['vehicle'] )
User.create(nickname: 'Santa', email: 'mark.valentino@email.com', name: 'Mark Valentino', first_name: 'Mark', last_name: 'Valentino', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 36, has_tags: ['vehicle, bike'], want_tags: ['housing'] )
User.create(nickname: 'Rudolph', email: 'rudy.giuliani@gmail.com', name: 'Rudy Giuliani', first_name: 'Rudy', last_name: 'Giuliani', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 37, has_tags: ['housing, topical'], want_tags: ['topical, bike'] )
User.create(nickname: 'Madonna', email: 'lourdes.ciccone@email.com', name: 'Lourdes Ciccone', first_name: 'Lourdes', last_name: 'Ciccone', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'New York, NY', gender: 'F', uid: 38, has_tags: ['topical'], want_tags: ['vehicle, topical'] )
User.create(nickname: 'Big Pun', email: 'jerry.mcguire@gmail.com', name: 'Jerry McGuire', first_name: 'Jerry', last_name: 'McGuire', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 39, has_tags: ['vehicle, topical'], want_tags: ['bike, topical'] )
User.create(nickname: 'Plato', email: 'michael.johnson@gmail.com', name: 'Michael Johnson', first_name: 'Michael', last_name: 'Johnson', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'New York, NY', gender: 'M', uid: 40, has_tags: ['vehicle, housing'], want_tags: ['bike'] )
User.create(nickname: 'Popsicle', email: 'calvin.klein@gmail.com', name: 'Calvin Klein', first_name: 'Calvin', last_name: 'Klein', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 41, has_tags: ['bike, topical'], want_tags: ['vehicle, housing'])
User.create(nickname: 'Mayo', email: 'marilyn.monroe', name: 'Marilyn Monroe', first_name: 'Marilyn', last_name: 'Monroe', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Baltimore, MD', gender: 'F', has_tags: ['topical, bike'], uid: 42, want_tags: ['topical, vehicle'] )
User.create(nickname: 'Switch', email: 'freedom.vehiclepenter@gmail.com', name: 'Freedom vehiclepenter', first_name: 'Freedom', last_name: 'vehiclepenter', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 43, has_tags: ['vehicle, topical'], want_tags: ['topical, pet'] )
User.create(nickname: 'Worm', email: 'derik.im@gmail.com', name: 'Derik Im', first_name: 'Derik', last_name: 'Im', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 44, has_tags: ['vehicle, bike, topical'], want_tags: ['topical'] )
User.create(nickname: 'Bunny', email: 'bonnie.bert@gmail.com', name: 'Bonnie Bert', first_name: 'Bonnie', last_name: 'Bert', profile_pic: 'http://www.utc.edu/health-human-performance/images/profiles/melissa-powell.jpg', location: 'Baltimore, MD', gender: 'F', uid: 45, has_tags: ['vehicle, housing, topical'], want_tags: ['topical, pet'] )
User.create(nickname: 'Captain', email: 'theodore.roosevelt@gmail.com', name: 'Theodore Roosevelt', first_name: 'Theodore', last_name: 'Roosevelt', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 46, has_tags: ['vehicle, pet'], want_tags: ['bike, housing'] )
User.create(nickname: 'DaVinci', email: 'leo.dicaprio@gmail.com', name: 'Leo Dicaprio', first_name: 'Leo', last_name: 'Dicaprio', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 47, has_tags: ['housing, pet'], want_tags: ['bike, vehicle'] )
User.create(nickname: 'Eli', email: 'elie.schoppik@email.com', name: 'Elie Schoppik', first_name: 'Elie', last_name: 'Schoppik', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 48, has_tags: ['vehicle, topical'], want_tags: ['bike, topical'] )
User.create(nickname: 'Zero', email: 'eddie.mustafa@gmail.com', name: 'Eddie Mustafa', first_name: 'Eddie', last_name: 'Mustafa', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 49, has_tags: ['bike, vehicle, topical'], want_tags: ['topical, housing'] )
User.create(nickname: 'Hero', email: 'hiro.sawada@gmail.com', name: 'Hiro Sawada', first_name: 'Hiro', last_name: 'Sawada', profile_pic: 'http://assets.bellmedia.ca.s3.amazonaws.com/uploads/2014/06/Scott-Henderson_1_2013-200x200.jpg', location: 'Baltimore, MD', gender: 'M', uid: 50, has_tags: ['bike, housing, topical'], want_tags: ['topical'] )

Resource.create(user_id: 1, category: "vehicle", has: true)
Resource.create(user_id: 1, category: "bike", has: true)
Resource.create(user_id: 1, category: "housing", has: true)
Resource.create(user_id: 1, category: "topical", has: true)
Resource.create(user_id: 1, category: "pet", has: true)








