# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(nickname:'Blossom', email: 'amy.lewis@email.com', name: 'Amy Lewis', first_name: 'Amy', last_name: 'Lewis', profile_pic: '', location: 'Los Angeles, CA', gender: 'F', has_tags: 'car, bike, pet', want_tags: 'topical, housing' )
User.create(nickname: 'CareBear', email: 'jenny.kim@email.com', name: 'Jenny Kim', first_name: 'Jenny', last_name: 'Kim', profile_pic: '', location: 'Los Angeles, CA', gender: 'F', has_tags: 'car, bike', want_tags: 'pet, topical' )
User.create(nickname: 'Jetson', email: 'michael.vallejo@email.com', name: 'Michael Vallejo', first_name: 'Michael', last_name: 'Vallejo', profile_pic: '', location: 'Los Angeles, CA', gender: '', has_tags: 'bike, housing', want_tags: 'housing, pet, topical' )
User.create(nickname: 'Scooby', email: 'sam.min@email.com', name: 'Sam Min', first_name: 'Sam', last_name: 'Min', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'car, housing', want_tags: 'bike, housing' )
User.create(nickname: 'Candyman', email: 'eugene.choi@email.com', name: 'Eugene Choi', first_name: 'Eugene', last_name: 'Choi', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'car, housing', want_tags: 'bike, housing' )
User.create(nickname: 'The Duke', email: 'george.sasscer@gmail.com', name: 'Geoerge Sasscer', first_name: 'George', last_name: 'Sasscer', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'car, housing, pet', want_tags: 'bike, housing, pet' )
User.create(nickname: 'The Duchess', email: 'Jackie Sasscer', name: 'Jackie Sasscer', first_name: 'Jackie', last_name: 'Sasscer', profile_pic: '', location: 'Los Angeles, CA', gender: 'F', has_tags: 'pet, housing, car', want_tags: 'bike, housing' )
User.create(nickname: 'Ghostbuster', email: 'bill.oreilly@email.com', name: 'Bill O\'Reilly', first_name: 'Bill', last_name: 'O\'Reilly', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'housing, car', want_tags: 'pet, topical' )
User.create(nickname: 'Han Solo', email: 'doug.funny@email.com', name: 'Doug Funny', first_name: 'Doug', last_name: 'Funny', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'housing, car, pet', want_tags: 'topical, bike' )
User.create(nickname: 'Taco', email: 'lionel.ritchie@email.com', name: 'Lionel Ritchie', first_name: 'Lionel', last_name: 'Ritchie', profile_pic: '', location: 'Los Angeles, CA', gender: 'M', has_tags: 'car, pet', want_tags: 'housing, topical' )
User.create(nickname: 'Princess Leia', email: 'erin.huie@gmail.com', name: 'Erin Huie', first_name: 'Erin', last_name: 'Huie', profile_pic: '', location: 'San Francisco, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Foo', email: 'eugene.choi@email.com', name: 'Eugene Choi', first_name: 'Eugene', last_name: 'Choi', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'bike, car', want_tags: 'housing, pet, topical' )
User.create(nickname: 'Mario', email: 'ken.burns@email.com', name: 'Ken Burns', first_name: 'Ken', last_name: 'Burns', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'topical, bike, car, housing', want_tags: 'topical, housing, car' )
User.create(nickname: 'Luigi', email: 'kevin.hart@gmail.com', name: 'Kevin Hart', first_name: 'Kevin', last_name: 'Hart', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'topical, bike, housing', want_tags: 'housing, pet, topical' )
User.create(nickname: 'Captain Kirk', email: 'james.t.kirk@gmail.com', name: 'James T. Kirk', first_name: 'James', last_name: 'Kirk', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'topical, pet, housing', want_tags: 'topical, bike' )
User.create(nickname: 'Sulu', email: 'george.takei@email.com', name: 'George Takei', first_name: 'George', last_name: 'Takei', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'bike, topical, housing', want_tags: 'topical, pet, housing' )
User.create(nickname: 'Penny', email: 'penny.loafer@gmail.com', name: 'Penelope Lee', first_name: 'Penelope', last_name: 'Lee', profile_pic: '', location: 'San Francisco, CA', gender: 'F', has_tags: 'bike, topical, housing', want_tags: 'topical, car' )
User.create(nickname: 'Manny', email: 'emmanuel.lee@email.com', name: 'Emmanuel Lee', first_name: 'Emmanuel', last_name: 'Lee', profile_pic: '', location: 'San Francisco, CA', gender: 'M', has_tags: 'bike, housing, topical', want_tags: 'topical, car, housing' )
User.create(nickname: 'Granny', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'San Francisco, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Hunter', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'San Francisco, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: '', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Oakland, CA', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'ZealousHacker', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'RadarScreen', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Waldo', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Princess', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Bologna', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Santa', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Rudolph', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Madonna', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Big Pun', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Plato', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'New York, NY', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Popsicle', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Mayo', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Switch', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Worm', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Bunny', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Captain', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'DaVinci', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'GA', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Zero', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )
User.create(nickname: 'Hero', email: 81831000, name: '', first_name: '', last_name: '', profile_pic: '', location: 'Baltimore, MD', gender: '', has_tags: '', want_tags: '' )

